"use client";
import { useEffect, useState } from "react";
import { Pencil, Trash2 } from "lucide-react";
import AuthGuard from "@/components/AuthGuard";
import AppShell from "@/components/AppShell";
import { supabase } from "@/lib/supabase";
import type { Entity } from "@/lib/types";
const types = [{v:"person",l:"Persona"},{v:"property",l:"Immobile"},{v:"vehicle",l:"Veicolo"},{v:"organization",l:"Organizzazione"},{v:"contract",l:"Contratto"},{v:"other",l:"Altro"}];
export default function EntitiesPage(){const [items,setItems]=useState<Entity[]>([]);const [editing,setEditing]=useState<Entity|null>(null);const [name,setName]=useState("");const [type,setType]=useState<Entity["entity_type"]>("person");const [description,setDescription]=useState("");const [message,setMessage]=useState("");
 async function load(){const {data,error}=await supabase.from("entities").select("*").order("name");if(error)setMessage(error.message);setItems((data??[]) as Entity[])} useEffect(()=>{load()},[]);
 function start(e?:Entity){setEditing(e??null);setName(e?.name??"");setType(e?.entity_type??"person");setDescription(e?.description??"");setMessage("")}
 async function save(ev:React.FormEvent){ev.preventDefault();setMessage("");const {data:u}=await supabase.auth.getUser();if(!u.user){setMessage("Sessione scaduta.");return}const payload={user_id:u.user.id,name:name.trim(),entity_type:type,description:description.trim()||null};const q=editing?await supabase.from("entities").update(payload).eq("id",editing.id):await supabase.from("entities").insert(payload);if(q.error)setMessage(q.error.message);else{start();load()}}
 async function remove(e:Entity){if(!confirm(`Eliminare ${e.name}? Le scadenze collegate resteranno senza associazione.`))return;const {error}=await supabase.from("entities").delete().eq("id",e.id);if(error)setMessage(error.message);else load()}
 return <AuthGuard><AppShell><h1 className="text-3xl font-bold">Persone e beni</h1><p className="text-slate-500">Gestisci ciò a cui sono collegate le scadenze.</p><form onSubmit={save} className="card mt-6 grid gap-3 p-5 md:grid-cols-[1fr_180px_1fr_auto]"><input className="input" placeholder="Nome (es. Casa Firenze)" value={name} onChange={e=>setName(e.target.value)} required maxLength={120}/><select className="input" value={type} onChange={e=>setType(e.target.value as Entity["entity_type"])}>{types.map(t=><option key={t.v} value={t.v}>{t.l}</option>)}</select><input className="input" placeholder="Descrizione facoltativa" value={description} onChange={e=>setDescription(e.target.value)} maxLength={500}/><button className="button-primary">{editing?"Salva":"Aggiungi"}</button>{editing&&<button type="button" className="button-secondary" onClick={()=>start()}>Annulla</button>}</form>{message&&<p className="mt-3 text-sm text-slate-600">{message}</p>}<div className="card mt-6 divide-y divide-slate-100 p-5">{!items.length&&<p className="text-slate-500">Nessuna entità configurata.</p>}{items.map(e=><div key={e.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><p className="font-semibold">{e.name}</p><p className="text-sm text-slate-500">{types.find(t=>t.v===e.entity_type)?.l}{e.description?` · ${e.description}`:""}</p></div><div className="flex gap-2"><button className="button-secondary" onClick={()=>start(e)}><Pencil size={16}/> Modifica</button><button className="button-secondary text-red-600" onClick={()=>remove(e)}><Trash2 size={16}/> Elimina</button></div></div>)}</div></AppShell></AuthGuard>}
